"""auto migrate

Revision ID: 461986601e36
Revises: d6773c73734d
Create Date: 2025-05-26 21:11:40.837986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461986601e36'
down_revision = 'd6773c73734d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
